<a href="https://colab.research.google.com/github/mehdiabbasidev/darsman-deep-learning/blob/main/MLP_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

## Ex1 : MLP

In [9]:
x = torch.randint(low=-10,high=10,size=(40,2),dtype=torch.float)
print(f"x :\n{x}")

model1 = nn.Linear(2, 5)
model2 = nn.Linear(5, 3)
model3 = nn.Linear(3, 1, bias=False)

mlp = nn.Sequential(model1,model2,model3)
print(f"\nMLP :\n{mlp}")
print(f"bias:\n{mlp[0].bias}")
print(f"weight:\n{mlp[0].weight}")
print(f"bias:\n{mlp[1].bias}")
print(f"weight:\n{mlp[1].weight }")
print(f"bias:\n{mlp[2].bias}")
print(f"weight:\n{mlp[2].weight }")


output=mlp(x)
print(f"\nOutput :\n{output}")

x :
tensor([[ -4.,   7.],
        [ -7.,  -6.],
        [ -8.,   9.],
        [ -9.,  -6.],
        [ -9.,   0.],
        [ -7.,  -9.],
        [  9.,   1.],
        [ -4.,   6.],
        [  8.,  -8.],
        [ -1.,   6.],
        [ -1.,  -9.],
        [  9.,  -4.],
        [ -2.,   4.],
        [  1.,   6.],
        [ -2.,   8.],
        [  3.,  -6.],
        [  9.,  -4.],
        [  1.,   7.],
        [ -1.,   5.],
        [-10.,  -4.],
        [ -5.,   1.],
        [  8.,   7.],
        [ -4.,   1.],
        [  2.,   9.],
        [  9.,   4.],
        [ -9.,   3.],
        [  1.,  -7.],
        [  6.,   9.],
        [  4.,   5.],
        [  6.,  -4.],
        [  0.,   0.],
        [  8.,  -9.],
        [  2.,   6.],
        [ -1.,   6.],
        [ -9.,  -5.],
        [ -8.,  -6.],
        [ -8., -10.],
        [-10.,  -4.],
        [  1.,   2.],
        [  9.,  -7.]])

MLP :
Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): Linear(in_features=5, out_feature

## EX2 : MLP & Loss & Optimizer

In [ ]:
sample_num=40
feature_num=3
target_num=5
eta = 0.02
N = 100

x = torch.randint(low=-10,high=10,size=(sample_num,feature_num),dtype=torch.float)
yt = torch.randn(sample_num, target_num)

model1 = nn.Linear(feature_num, 7)
model2 = nn.Linear(7, target_num, bias=False)
mlp = nn.Sequential(model1,model2)
# print(f"bias:\n{mlp[0].bias}")
# print(f"weight:\n{mlp[0].weight}")
# print(f"bias:\n{mlp[1].bias}")
# print(f"weight:\n{mlp[1].weight }")


loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(mlp.parameters(), lr=eta)

loss_list=[]
for epoch in range(N):
    yp = mlp(x)
    loss = loss_fn(yp, yt)
    loss_list.append(loss.item())
    print(f"Epoch {epoch+1} => Loss: {loss.item():.6f}")
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

plt.plot(range(N), loss_list)
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Learning Curve on Loss Values')
plt.show()

## Ex3 : MLP Class - Two Layer Model

In [ ]:
import torch
import torch.nn as nn

class TwoLayerModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(TwoLayerModel, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = torch.relu(self.layer1(x))
        x = self.layer2(x)
        return x


model = TwoLayerModel(input_size=2, hidden_size=5, output_size=3)
x1 = torch.tensor([-7., -2.])
output1 = model(x1)
print(f"x1:\n{ x1}",)
print(f"Output1:\n{ output1}",)

print(100*"*")

x2 = torch.randint(low=-10,high=10,size=(20,2),dtype=torch.float)
output2 = model(x2)
print(f"x2:\n{ x2}",)
print(f"Output2:\n{ output2}",)

## Ex4 : MLP Class - Dynamic Layer Model

In [18]:
import torch
import torch.nn as nn

class DynamicLayerModel(nn.Module):
    def __init__(self, layer_sizes):
        super(DynamicLayerModel, self).__init__()
        self.layers = nn.ModuleList()
        for i in range(len(layer_sizes) - 1):
            self.layers.append(nn.Linear(layer_sizes[i], layer_sizes[i + 1]))


    def forward(self, x):
        for i, layer in enumerate(self.layers):
            x = layer(x) if i == len(self.layers) - 1 else torch.relu(layer(x))
        return x


layer_sizes = [2, 5, 3, 1]                # [input_size, hidden1, hidden2, ..., output_size]
model = DynamicLayerModel(layer_sizes)

x3 = torch.randint(low=-10,high=10,size=(20,2),dtype=torch.float)
output3 = model(x3)
print(f"x2:\n{ x3}",)
print(f"Output2:\n{ output3}",)

x2:
tensor([[  5.,   3.],
        [ -3.,   7.],
        [  8.,  -1.],
        [  6.,   3.],
        [ -4.,   9.],
        [  8.,  -4.],
        [  2.,   9.],
        [  6.,  -9.],
        [ -6.,  -2.],
        [  2.,  -2.],
        [  9.,  -6.],
        [-10.,   5.],
        [ -4.,  -5.],
        [  1.,   2.],
        [  0.,  -3.],
        [ -8.,  -3.],
        [  6.,  -7.],
        [  2., -10.],
        [ -4.,   8.],
        [ -8.,  -8.]])
Output2:
tensor([[-0.5774],
        [-0.2162],
        [-0.6954],
        [-0.6276],
        [-0.2012],
        [-0.3791],
        [-0.4687],
        [-0.2446],
        [-0.2440],
        [-0.2445],
        [-0.2446],
        [-0.2337],
        [-0.2446],
        [-0.3698],
        [-0.2446],
        [-0.2446],
        [-0.2446],
        [-0.2446],
        [-0.2059],
        [-0.2446]], grad_fn=<AddmmBackward0>)
