<a href="https://colab.research.google.com/github/mehdiabbasidev/darsman-deep-learning/blob/main/NeuronObject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [8]:
class Neuron:
    def __init__(self, n, af='linear'):
        self.w = torch.randn(n, requires_grad=True)
        self.b = torch.randn(1, requires_grad=True)
        self.af = af

    def __call__(self, X):
        z = self.w @ X + self.b
        print(f"w : {self.w}")
        print(f"b : {self.b.item()}")
        print(f"z : {z.item()}")
        match self.af:
            case 'linear':
                return self.linear(z)
            case 'step':
                return self.step(z)
            case 'relu':
                return self.relu(z)
            case 'sigmoid':
                return self.sigmoid(z)
            case _:
                raise ValueError(f"Unsupported activation function: {self.af}")

    def linear(self, x):
        return x

    def step(self, x):
        return (x > 0).float()

    def relu(self, x):
        return torch.maximum(x, torch.tensor(0.0))      # torch.relu(x)

    def sigmoid(self, x):
        return 1 / (1 + torch.exp(-x))                  # torch.sigmoid(x)


In [9]:
X = torch.tensor([3., 2., 1., 2., 0.])
y = torch.tensor([0.3])

print(f"X :\n{X}")
print(f"y :\n{y}")

X :
tensor([3., 2., 1., 2., 0.])
y :
tensor([0.3000])


In [16]:
neuron1 = Neuron(5, 'sigmoid')
print(f"neuron :\n{neuron1}")

neuron :


In [17]:
y_pred = neuron1(X)
print(f"y_pred : {y_pred.item()}")

w : tensor([ 0.5370,  1.8492,  0.6938, -0.5032,  1.3542], requires_grad=True)
b : 1.3396143913269043
z : 6.33629035949707
y_pred : 0.9982323050498962


In [18]:
mse_loss=(y_pred- y)**2
mse_loss

tensor([0.4875], grad_fn=<PowBackward0>)

In [23]:
n2=Neuron(3)
y_pred =n2(torch.tensor([1.2,0.23,4.1]))
print(f"y_pred : {y_pred.item()}")

mse_loss=(y_pred- y)**2
print(mse_loss)

w : tensor([ 0.3288,  1.0608, -0.6226], requires_grad=True)
b : -0.35041967034339905
z : -2.2646453380584717
y_pred : -2.2646453380584717
tensor([6.5774], grad_fn=<PowBackward0>)
